version: 2

models:
  - name: stg_zones
    columns:
      - name: location_id
        tests:
          - not_null
          - unique

  - name: stg_yellow_trips
    columns:
      - name: pickup_ts
        tests:
          - not_null
      - name: dropoff_ts
        tests:
          - not_null
      - name: pu_location_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_zones')
              field: location_id
      - name: do_location_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_zones')
              field: location_id
